---
- name: Download the wallpaper image and user image
  get_url:
    url: "{{ item.download }}"
    dest: "{{ item.location }}"
  with_items:
    - download: "{{ wallpaper }}"
      location: "~/Pictures/wallpaper"
    - download: "{{ user_image }}"
      location: "~/Pictures/{{ ansible_env.USER }}"


# - name: Resize the user image
#   shell: "convert ~/Pictures/{{ ansible_env.USER }} -resize 200x100 ~/Pictures/{{ ansible_env.USER }}"


- name: Set the wallpaper
  shell: "gsettings set org.gnome.desktop.background picture-uri file:///home/{{ ansible_env.USER }}/Pictures/wallpaper"


## Add custom font families
- name: Creates .fonts directory
  file: path=~/.fonts state=directory

- name: Download SF Mono font family
  get_url:
    url: https://github.com/ZulwiyozaPutra/SF-Mono-Font/archive/master.zip
    dest: ~/
    
- name: Unzip SF Mono font family
  unarchive:
    src:  ~/SF-Mono-Font-master.zip
    dest: ~/.fonts

- name: Refresh font cache
  shell: fc-cache -f -v


# - name: Set the user image
#   copy:
#     src: ~/Pictures/{{ ansible_env.USER }}
#     dest: /var/lib/AccountsService/icons/{{ ansible_env.USER }}
#   become: true


