---
- name: Download the wallpaper image and user image
  get_url:
    url: "{{ item.download }}"
    dest: "{{ item.location }}"
  with_items:
    - download: "{{ wallpaper }}"
      location: "~/Pictures/wallpaper"
    - download: "{{ user_image }}"
      location: "~/Pictures/{{ ansible_env.USER }}"


- name: Resize the user image
  shell: "convert ~/Pictures/{{ ansible_env.USER }} -resize 200x100 ~/Pictures/{{ ansible_env.USER }}"


- name: Set the wallpaper
  shell: "gsettings set org.gnome.desktop.background picture-uri file:///home/{{ ansible_env.USER }}/Pictures/wallpaper"


- name: Set the user image
  copy:
    src: ~/Pictures/{{ ansible_env.USER }}
    dest: /var/lib/AccountsService/icons/{{ ansible_env.USER }}
  become: true


