---
- name: Download the wallpaper image and user image
  get_url:
    url: "{{ item.download }}"
    dest: "{{ item.location }}"
  with_items:
    - download: "{{ wallpaper }}"
      location: "~/theme/wallpaper.png"
    - download: "{{ user_image }}"
      location: "~/theme/me.png"


- name: Set the wallpaper
  shell: "gsettings set org.gnome.desktop.background picture-uri file:///home/{{ ansible_env.USER }}/theme/{{ wallpaper_file }}"


- name: Set the user image
  copy:
    src: ~/theme/{{ userimage_file }}.png
    dest: /var/lib/AccountsService/icons/{{ ansible_env.USER }}.png
  become: true


