---
- name: Batcave development environment
  hosts: localhost
  vars_files:
    - vars/main.yml
    - vars/nodejs.yml
    - vars/visual-studio-code.yml
  roles:
    - { role: desktop-cleanup, become: true }
    # https://github.com/geerlingguy/ansible-role-nodejs
    - { role: nodejs, become: true }
    # https://github.com/gantsign/ansible-role-visual-studio-code
    - { role: visual-studio-code, become: true }

