---
- hosts: all
  roles:
    - role: desktop-cleanup
      become: true
    - role: nodejs                 # https://github.com/geerlingguy/ansible-role-nodejs
    - role: visual-studio-code     # https://github.com/gantsign/ansible-role-visual-studio-code

