---
- hosts: all
  roles:
    - role: desktop-cleanup
      become: true

    # https://github.com/geerlingguy/ansible-role-nodejs
    - role: nodejs

    # https://github.com/gantsign/ansible-role-visual-studio-code
    - role: visual-studio-code
