---
- hosts: all
  roles:
    - desktop-cleanup

    # https://github.com/geerlingguy/ansible-role-nodejs
    - nodejs

    # https://github.com/gantsign/ansible-role-visual-studio-code
    - visual-studio-code
