---
- name: Batcave development environment
  hosts: localhost
  
  vars_files:
    - vars/main.yml
    
  vars_prompt:
  - name: "github_username"
    prompt: "What is your github username"
    private: no
  - name: "github_token"
    prompt: "What is your github personal access token ( GPG and SSH )"
    private: yes
  - name: "ssh_password"
    prompt: "Please enter a secure SSH private key password"
    private: yes
    confirm: yes
  - name: "gpg_password"
    prompt: "Please enter a secure GPG private key password"
    private: yes
    confirm: yes
    
  roles:
    # Apply theme
    - { role: theme }
    # Get dotfiles from github
    - { role: dotfiles }
    # Create a ssh key and gpg key, add them to the keychain
    - { role: keys-generate }
    # Add ssh key and gpg credentials to github account
    - { role: keys-deploy }
    # Clone github projects
    - { role: github-projects }
    # Install nodejs
    - { role: nodejs, become: true }
    # Install VSC
    - { role: visual-studio-code, become: true }
    # Clean up the ubuntu desktop environment, install packages, update packages
    - { role: desktop-cleanup, become: true }
