---
- name: Batcave development environment
  hosts: localhost
  vars_files:
    - vars/main.yml
  roles:
    # Clean up the ubuntu desktop environment, install packages, update packages
    - { role: desktop-cleanup, become: true }
    # Add ssh key and gpg credentials to github account
    - { role: ssh-key }
    # Add ssh key and gpg credentials to github account
    # - { role: github, become: true }
    # Clone github projects
    # - { role: github-projects }
    # Install nodejs
    # - { role: nodejs, become: true }
    # Install VSC
    # - { role: visual-studio-code, become: true }
