---
# https://superuser.com/questions/1003403/how-to-use-gpg-gen-key-in-a-script
- name: Create gpgdetails file
  copy:
    dest: ~/.gpgdetails
    content: |
      Key-Type: RSA
      Key-Length: 4096
      Subkey-Type: RSA
      Subkey-Length: 4096
      Name-Email: { email }
      Expire-Date: 0
      Passphrase: { key_passphrase }
  no_log: true


- name: Generate GPG file, remove gpgdetails
  shell: |
    gpg --batch --gen-key ~/.gpgdetails
    rm ~/.gpgdetails
