---
# https://superuser.com/questions/1003403/how-to-use-gpg-gen-key-in-a-script
- name: Create gpgdetails file
  template:
    src: ".gpgdetails"
    dest: "~/.gpgdetails"
    mode: 0600
  # no_log: true


- name: Generate GPG key and remove gpgdetails
  shell: gpg --batch --gen-key ~/.gpgdetails && rm ~/.gpgdetails
