---

- name: Install packages for ssh key management
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - keychain  # gpg and ssh key management
    - expect    # ssh add-key without prompts private key to keychain
    - curl      # send public key data to github

- name: Creating SSH key for current user
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: "{{ key_passphrase }}"
    ssh_key_comment: "{{ email }}"
  no_log: true


- name: Reset the bashrc so we can use keychain
  command: source ~/.bashrc


# This requires keychain
- name: Start the ssh-agent
  command: eval "$(ssh-agent -s)"


# This requires expect
# https://unix.stackexchange.com/questions/90853/how-can-i-run-ssh-add-automatically-without-password-prompt
- name: Add private key to ssh-agent
  shell: |
    spawn ssh-add ~/.ssh/id_rsa
    expect "Enter passphrase for ~/.ssh/id_rsa:"
    send "{{ ssh_passphrase }}\n";
    expect "Identity added: ~/.ssh/id_rsa (~/.ssh/id_rsa)"
    interact
  no_log: true
