---
- name: Creating SSH key for current user
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: "{{ key_passphrase }}"
    ssh_key_comment: "{{ email }}"


# https://superuser.com/questions/1003403/how-to-use-gpg-gen-key-in-a-script
- name: Create gpgdetails file
  copy:
    dest: ~/.gpgdetails
    content: |
      Key-Type: RSA
      Key-Length: 4096
      Subkey-Type: RSA
      Subkey-Length: 4096
      Name-Email: "{{ email }}"
      Expire-Date: 0
      Passphrase: "{{ key_passphrase }}"


- name: Generate GPG file, remove gpgdetails
  shell: |
    gpg --batch --gen-key ~/.gpgdetails
    rm ~/.gpgdetails


# This requires keychain
- name: Start the ssh-agent
  command: eval "$(ssh-agent -s)"


# This requires expect
# https://unix.stackexchange.com/questions/90853/how-can-i-run-ssh-add-automatically-without-password-prompt
- name: Add private key to ssh-agent
  shell: |
    spawn ssh-add ~/.ssh/id_rsa
    expect "Enter passphrase for ~/.ssh/id_rsa:"
    send "{{ ssh_passphrase }}\n";
    expect "Identity added: ~/.ssh/id_rsa (~/.ssh/id_rsa)"
    interact
