---
- name: Install packages for ssh key management
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - keychain  # gpg and ssh key management
    - expect    # ssh add-key without prompts private key to keychain
    - curl      # send public key data to github
  become: true


- name: Creating SSH key for current user
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: "{{ key_passphrase }}"
    ssh_key_comment: "{{ email }}"
  no_log: true


# https://stackoverflow.com/questions/41379083/sourcing-a-file-before-executing-commands-in-ansible
# https://unix.stackexchange.com/questions/90853/how-can-i-run-ssh-add-automatically-without-password-prompt
- name: Start the ssh-agent and add the private key to ssh-agent
  script: ../addkey.sh
  become: true
  no_log: true
  environment:
    KEY: "{{ key_passphrase }}"
    USER: "{{ ansible_env.USER }}"
