---

- name: Remove unecessary applications
  apt: pkg={{ item }} purge=yes state=absent
  with_items:
    - aisleriot
    - cheese
    - firefox
    - gnome-mahjongg
    - gnome-mines
    - gnome-sudoku
    - gnome-software-editor
    - help
    - libmediascanner-2.0-0
    - libreoffice*
    - libwacom*
    - mediascanner2.0
    - remmina
    - rhythmbox*
    - shotwell*
    - thunderbird
    - transmission-gtk
    - ubuntu-amazon-default
    - ubuntu-web-launchers
    - unity-lens-shopping
    - unity-scope-gdrive
    - unity-scope-gmusicbrowser
    - unity-scope-googlenews
    - unity-scope-gourmet
    - unity-scope-guayadeque
    - unity-scope-launchpad
    - unity-scope-musicstores
    - unity-scope-musicstores
    - unity-scope-musique
    - unity-scope-onlinemusic
    - unity-scope-video-remote
    - unity-scope-yahoostock
    - xserver-xorg-input-wacom
    - vino-preferences
    - yelp

- name: Remove unecessary files and directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/Examples
    - /usr/share/example-content


- name: Remove amazon shortcut from launch bar
  file: path=/usr/share/applications/ubuntu-amazon-default.desktop force=yes state=absent


- name: Disable unity integrations
  command: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"


- name: Remove user directories ( XDG )
  file: path="{{ ansible_env.HOME }}/{{ item }}" force=yes state=absent
  with_items:
    - Pictures
    - Videos
    - Music
    - Public
    - Templates


- name : Run xdg-user-dirs-update
  shell: xdg-user-dirs-update
  become: true
  become_user: "{{ ansible_env.USER }}"
