---

- name: Ensure Unity MediaScanner is removed (useless + cause high CPU peaks)
  apt: pkg={{ item }} purge=yes state=absent
  with_items:
    - mediascanner2.0
    - libmediascanner-2.0-0

- name: Remove unecessary applications
  apt: pkg={{ item }} purge=yes state=absent
  with_items:
    - unity-lens-shopping
    - unity-scope-video-remote
    - unity-scope-musicstores
    - unity-scope-gdrive
    - unity-scope-gmusicbrowser
    - unity-scope-gourmet
    - unity-scope-guayadeque
    - unity-scope-musicstores
    - unity-scope-musique
    - unity-scope-googlenews
    - unity-scope-launchpad
    - unity-scope-onlinemusic
    - unity-scope-yahoostock
    - aisleriot
    - gnome-mahjongg
    - gnome-mines
    - gnone-sudoku
    - cheese
    - help
    - libreoffice*
    - rhythmbox*
    - libwacom*
    - xserver-xorg-input-wacom

- name: Remove desktop shortcut
  command:
    - file: "{{ item }}"
  with_items:
    - path=/usr/share/applications/ubuntu-amazon-default.desktop force=yes state=absent
    - path=/usr/share/applications/help.desktop force=yes state=absent
    - path=/usr/share/applications/rhythmbox.desktop force=yes state=absent
    - path="{{ ansible_env.HOME }}/examples.desktop" force=yes state=absent

- name: Disable unity integrations
  command: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - apt purge ubuntu-web-launchers
    - gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"

- name: Remove user directories ( XDG )
  file: path="{{ ansible_env.HOME }}/{{ item }}" force=yes state=absent
  with_items:
    - Examples
    - Pictures
    - Videos
    - Music
    - Public
    - Templates

- name : Run xdg-user-dirs-update
  shell: xdg-user-dirs-update
  become: true
  become_user: "{{ ansible_env.USER }}"
