---

- name: Ensure Unity MediaScanner is removed (useless + cause high CPU peaks)
  apt: pkg={{ item }} purge=yes state=absent
  with_items:
    - mediascanner2.0
    - libmediascanner-2.0-0

- name: Remove unecessary unity plugins
  apt: pkg={{ item }} purge=yes state=absent
  with_items:
    - unity-lens-shopping
    - unity-scope-video-remote
    - unity-scope-musicstores
    - unity-scope-gdrive
    - unity-scope-gmusicbrowser
    - unity-scope-gourmet
    - unity-scope-guayadeque
    - unity-scope-musicstores
    - unity-scope-musique
    - unity-scope-googlenews
    - unity-scope-launchpad
    - unity-scope-onlinemusic
    - unity-scope-yahoostock

- name: Remove amazon shortcut
  file: path=/usr/share/applications/ubuntu-amazon-default.desktop force=yes state=absent

- name: Disable unity integrations
  command: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - gsettings set com.canonical.Unity.webapps integration-allowed false
    - gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"
    - gsettings set com.canonical.Unity.webapps preauthorized-domains "[]"
    - gsettings set com.canonical.Unity.ApplicationsLens display-available-apps false

- name: Remove exemples shortcut
  file: path="{{ ansible_env.HOME }}/examples.desktop" force=yes state=absent

- name: Remove user directories ( XDG )
  file: path="{{ ansible_env.HOME }}/{{ item }}" force=yes state=absent
  with_items:
    - Examples
    - Pictures
    - Videos
    - Music
    - Public
    - Templates

- name : Run xdg-user-dirs-update
  shell: xdg-user-dirs-update
  become: true
  become_user: "{{ ansible_env.USER }}"
