---
# https://gist.github.com/mblarsen/62d2c0451e69a607a66a
- name: Cloning repositories from github
  git:
    repo: "git@github.com:{{ item.repo }}.git"
    dest: "{{ item.dest }}"
    force: yes
    recursive: no
    accept_hostkey: yes
    key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
  with_items:
    - "{{ github_projects }}"
